"""paper/tables/*.json -> paper/tables/numbers.tex (one LaTeX macro per number).

Every quantitative statement in paper/main.tex is a macro defined here, so the
manuscript cannot drift from the measured data. Macro names are letters only.
"""
from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
TAB = ROOT / "paper" / "tables"
ds = json.loads((TAB / "dataset_stats.json").read_text())
mm = json.loads((TAB / "model_metrics.json").read_text())
ops = json.loads((TAB / "bench_ops.json").read_text())
inf = json.loads((TAB / "bench_infer.json").read_text())
M: dict[str, str] = {}


def macro(name, value):
    assert name.isalpha(), name
    M[name] = str(value)


def thousands(n: int) -> str:
    return f"{n:,}".replace(",", "{,}")


# ---- dataset ----------------------------------------------------------------
macro("dsBones", ds["n_bones"]); macro("dsSubjects", ds["n_subjects"])
for s, tag in (("train", "Train"), ("val", "Val"), ("test", "Test")):
    macro(f"ds{tag}", ds["splits"][s]["bones"]); macro(f"ds{tag}Subj", ds["splits"][s]["subjects"])
macro("dsPtsPerBone", thousands(int(round(ds["points_per_bone"]["mean"]))))
macro("dsPtsTotalM", f"{ds['points_per_bone']['total'] / 1e6:.1f}")
macro("dsCerv", ds["regions"]["C"]); macro("dsThor", ds["regions"]["T"]); macro("dsLumb", ds["regions"]["L"])
macro("dsLevels", len(ds["levels"]))
short = {"Unlabeled": "Unl", "Superior_Endplate": "Sup", "Inferior_Endplate": "Inf", "Pedicle": "Ped",
         "Body_Wall": "Body", "Spinous_Process": "Spin"}
for name, frac in zip(ds["class_names"], ds["class_fraction"]):
    macro(f"frac{short[name]}", f"{100 * frac:.1f}")
macro("catClouds", ds["catalog"]["clouds"]); macro("catProjects", ds["catalog"]["projects"])
macro("catModels", ds["catalog"]["models"]); macro("catLabelFiles", thousands(ds["catalog"]["label_files"]))

# ---- interaction latency ----------------------------------------------------
macro("opsPointsM", f"{ops['n_points'] / 1e6:.0f}")
for k, tag in (("pick", "Pick"), ("box", "Box"), ("lasso", "Lasso"), ("brush", "Brush"),
               ("apply", "Apply"), ("undo", "Undo"), ("redo", "Redo")):
    v = ops["ops"][k]["ms"]
    macro(f"ops{tag}Ms", f"{v:.1f}" if v < 10 else f"{v:.0f}")
macro("opsRepeats", ops["repeats"])
macro("opsSlowestMs", f"{max(o['ms'] for o in ops['ops'].values()):.0f}")

# ---- inference latency ------------------------------------------------------
macro("infMedianS", f"{inf['inference_s_median']:.1f}"); macro("infLoadS", f"{inf['model_load_s_median']:.0f}")
macro("infWallS", f"{inf['wall_s_median']:.0f}"); macro("infBones", inf["n_bones"])
macro("infGpu", inf["gpu"].replace("NVIDIA GeForce ", "")); macro("infPts", thousands(int(inf["points_mean"])))

# ---- models -----------------------------------------------------------------
macro("valBones", mm["models"]["sonata"]["summary"]["n_bones"])
macro("hiThresh", f"{mm['threshold']:.2f}")
for mid, tag in (("sonata", "son"), ("yamato", "yam")):
    m = mm["models"][mid]
    for cls, ctag in (("Superior_Endplate", "Sup"), ("Inferior_Endplate", "Inf"), ("Pedicle", "Ped")):
        c = m["classes"][cls]
        macro(f"{tag}{ctag}Prec", f"{c['precision']:.3f}"); macro(f"{tag}{ctag}Rec", f"{c['recall']:.3f}")
        macro(f"{tag}{ctag}Iou", f"{c['iou']:.3f}"); macro(f"{tag}{ctag}Hi", f"{c['hi_precision']:.3f}")
        macro(f"{tag}{ctag}HiKept", f"{c['hi_kept_per_bone']:.0f}")
        worst = min(b[cls]["precision"] for b in m["per_bone"] if b[cls]["precision"] is not None)
        macro(f"{tag}{ctag}Worst", f"{worst:.2f}")
    macro(f"{tag}MeanPrec", f"{m['summary']['mean_fg_precision']:.3f}")
    macro(f"{tag}MeanIou", f"{m['summary']['mean_fg_iou']:.3f}")
    macro(f"{tag}MeanHi", f"{m['summary']['mean_fg_hi_precision']:.3f}")
    macro(f"{tag}MiouSix", f"{m['val_miou_6class']:.3f}" if m["val_miou_6class"] else "--")
    ax = m["axis_summary"]
    macro(f"{tag}AxisS", f"{ax['S_deg']['median']:.2f}"); macro(f"{tag}AxisSNinety", f"{ax['S_deg']['p90']:.1f}")
    macro(f"{tag}AxisP", f"{ax['P_deg']['median']:.1f}"); macro(f"{tag}AxisPNinety", f"{ax['P_deg']['p90']:.1f}")
    macro(f"{tag}AxisC", f"{ax['C_mm']['median']:.2f}"); macro(f"{tag}AxisCNinety", f"{ax['C_mm']['p90']:.1f}")
    macro(f"{tag}AxisOk", ax.get("n_ok", "--"))
son, yam = mm["models"]["sonata"]["classes"], mm["models"]["yamato"]["classes"]
macro("dInfIou", f"{100 * (son['Inferior_Endplate']['iou'] - yam['Inferior_Endplate']['iou']):.1f}")
macro("dSupIou", f"{100 * (son['Superior_Endplate']['iou'] - yam['Superior_Endplate']['iou']):.1f}")
macro("dMiouSix", f"{100 * (mm['models']['sonata']['val_miou_6class'] - mm['models']['yamato']['val_miou_6class']):.1f}")

lines = ["% AUTO-GENERATED by scripts/paper_numbers.py — do not edit by hand."]
for k, v in M.items():
    lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
(TAB / "numbers.tex").write_text("\n".join(lines) + "\n")
print(f"wrote {len(M)} macros -> paper/tables/numbers.tex")
